### ISSUE TITLE
Getting php notice while saving the workflow

### ISSUE THREAD

**Issue by kavya1515** [Makewebbetter/abandoned-cart-for-woocommerce#73]
Notice: Undefined offset: 0 in /home/demomwb/public_html/userenv/demomwb_UhOVirWTUCRN/wp-content/plugins/abandoned-cart-for-woocommerce/admin/class-abandoned-cart-for-woocommerce-admin.php on line 477
https://nimb.ws/jeVvL0

**Comment by sumitshukla-cedcoss** [comment]
Issue Fixed
