### ISSUE TITLE
Issue with "discount % in email"

### ISSUE THREAD

**Issue by kavya1515** [Makewebbetter/abandoned-cart-for-woocommerce#83]
The discount % is not syncing with second and third email.Please see screenshots attached.
![screenshot-mail google com-2021 06 20-15_16_42](https://user-images.githubusercontent.com/63343498/122669386-b08c6a00-d1da-11eb-8cbb-583f1bb22757.png)
![screenshot-mail google com-2021 06 20-15_15_38](https://user-images.githubusercontent.com/63343498/122669387-b1bd9700-d1da-11eb-9859-34ba23a73417.png)

**Comment by sumitshukla-cedcoss** [comment]
Issue Fixed
