### ISSUE TITLE
Php notice on Home sub  menu

### ISSUE THREAD

**Issue by kavya-cedcoss** [Makewebbetter/abandoned-cart-for-woocommerce#88]
![screenshot-localhost_10010-2021 11 18-19_58_17 (1)](https://user-images.githubusercontent.com/63343498/142434934-f30cfd00-706b-4ad5-b129-2f5276530c8f.png)

Php Warning: A non-numeric value encountered in /home/cedcoss/Local Sites/zohocrm/app/public/wp-content/plugins/abandoned-cart-for-woocommerce/common/class-abandoned-cart-for-woocommerce-common.php on line 93

**Comment by kavya-cedcoss** [comment]
![screenshot-demo makewebbetter com-2021 11 23-14_38_03](https://user-images.githubusercontent.com/63343498/142996900-00c6ba65-723d-442a-a9a7-313a27b0aad4.png)

**Comment by sumitshukla-cedcoss** [comment]
@kavya-cedcoss Issue fixed
