### ISSUE TITLE
Plugin activation notice

### ISSUE THREAD

**Issue by kavya-cedcoss** [Makewebbetter/abandoned-cart-for-woocommerce#89]
When we try to activate plugin on main network site without activating woocommerce, it's not giving error notice
![screenshot-demo makewebbetter com-2021 11 22-15_53_00](https://user-images.githubusercontent.com/63343498/142848263-f273914a-fdc0-4d40-ae6d-c941fe127e29.png)
.

**Comment by sumitshukla-cedcoss** [comment]
@kavya-cedcoss Issue fixed
