### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by kavya-cedcoss** [Makewebbetter/abandoned-cart-for-woocommerce#91]
phpcs issue-
[abandon-org.xml.zip](https://github.com/Makewebbetter/abandoned-cart-for-woocommerce/files/7611691/abandon-org.xml.zip)
[abandon-pro.xml.zip](https://github.com/Makewebbetter/abandoned-cart-for-woocommerce/files/7611692/abandon-pro.xml.zip)

-remove unnecessary files and folders

-some syntax error in file abandoned-cart-for-woocommerce-overview.php line 47

-changes in main file and same changes in pro
Tested up to:      5.8.2
WC tested up to:    5.9.0

**Comment by sumitshukla-cedcoss** [comment]
Fixable issue are fixed
